import type { Snapshot } from "./types";

const av = (seed: string) =>
  `https://api.dicebear.com/9.x/notionists/svg?seed=${encodeURIComponent(seed)}&backgroundColor=eef2e9,f4eede,f5e6e0,e9eaf3,e3edf2`;

export const SEED: Snapshot = {
  users: [
    {
      id: "u_maya",
      username: "maya",
      name: "Maya Alvarez",
      bio: "Trying to see myself through clearer eyes.",
      avatar: av("maya-2"),
      joinedAt: "2026-04-02T14:00:00Z",
    },
    {
      id: "u_jordan",
      username: "jordan",
      name: "Jordan Pak",
      bio: "Curious about the gap between how I show up and how I think I show up.",
      avatar: av("jordan-7"),
      joinedAt: "2026-04-05T17:20:00Z",
    },
    {
      id: "u_sami",
      username: "sami",
      name: "Sami Okafor",
      bio: "Collecting honest reflections from people I trust.",
      avatar: av("sami-3"),
      joinedAt: "2026-04-08T09:45:00Z",
    },
    {
      id: "u_lena",
      username: "lena",
      name: "Lena Brooks",
      bio: "Reading people for a living. Curious how they read me.",
      avatar: av("lena-9"),
      joinedAt: "2026-04-10T22:10:00Z",
    },
    {
      id: "u_theo",
      username: "theo",
      name: "Theo Reyes",
      bio: "Quiet on purpose.",
      avatar: av("theo-4"),
      joinedAt: "2026-04-15T08:30:00Z",
    },
  ],
  prompts: [
    {
      id: "p_1",
      authorUsername: "maya",
      question: "What's something you think I'm quietly really good at?",
      category: "hidden-talents",
      image:
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80&auto=format&fit=crop",
      createdAt: "2026-04-26T15:00:00Z",
    },
    {
      id: "p_2",
      authorUsername: "jordan",
      question: "If you had to describe me in three words, what would they be?",
      category: "personality",
      createdAt: "2026-04-26T18:30:00Z",
    },
    {
      id: "p_3",
      authorUsername: "sami",
      question: "What's the first impression you remember getting from me?",
      category: "first-impressions",
      image:
        "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=800&q=80&auto=format&fit=crop",
      createdAt: "2026-04-27T12:15:00Z",
    },
    {
      id: "p_4",
      authorUsername: "lena",
      question: "Where do you think I shine without realizing it?",
      category: "strengths",
      createdAt: "2026-04-27T20:00:00Z",
    },
    {
      id: "p_5",
      authorUsername: "theo",
      question: "What's one thing you think I'm still figuring out?",
      category: "growth",
      createdAt: "2026-04-28T09:10:00Z",
    },
  ],
  responses: [
    {
      id: "r_1",
      promptId: "p_1",
      responderUsername: "jordan",
      text: "You make people feel like the most interesting person in the room without trying. It's a kind of generosity people don't usually name.",
      traits: ["generous", "thoughtful"],
      anonymous: false,
      createdAt: "2026-04-26T17:45:00Z",
      pinned: true,
    },
    {
      id: "r_2",
      promptId: "p_1",
      responderUsername: "lena",
      text: "Reading the temperature of a group. You always seem to know who needs to be pulled into the conversation.",
      traits: ["thoughtful", "kind"],
      anonymous: false,
      createdAt: "2026-04-27T10:02:00Z",
    },
    {
      id: "r_3",
      promptId: "p_2",
      responderUsername: "sami",
      text: "Steady. Funny in the dry way. Quietly competitive.",
      traits: ["steady", "funny", "driven"],
      anonymous: false,
      createdAt: "2026-04-26T21:11:00Z",
    },
    {
      id: "r_4",
      promptId: "p_2",
      responderUsername: "maya",
      text: "Honest, loyal, curious — in that order.",
      traits: ["honest", "loyal", "curious"],
      anonymous: false,
      createdAt: "2026-04-27T08:30:00Z",
      pinned: true,
    },
    {
      id: "r_5",
      promptId: "p_3",
      responderUsername: "theo",
      text: "I remember thinking you were going to be intimidating, and then within five minutes realizing you were the warmest person in the room.",
      traits: ["kind", "honest"],
      anonymous: false,
      createdAt: "2026-04-27T14:00:00Z",
    },
    {
      id: "r_6",
      promptId: "p_4",
      responderUsername: "maya",
      text: "You translate complicated ideas into something a tired person at the back of the room can still follow. That's rarer than you think.",
      traits: ["thoughtful", "creative"],
      anonymous: false,
      createdAt: "2026-04-27T22:48:00Z",
    },
    {
      id: "r_7",
      promptId: "p_5",
      responderUsername: "jordan",
      text: "When to stop optimizing and just enjoy the thing you've already built. You're closer than you think.",
      traits: ["honest"],
      anonymous: false,
      createdAt: "2026-04-28T11:30:00Z",
    },
  ],
};
